// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.strictfipsruntime
// +build goexperiment.strictfipsruntime

package goexperiment

const StrictFIPSRuntime = true
const StrictFIPSRuntimeInt = 1
