// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.strictfipsruntime
// +build !goexperiment.strictfipsruntime

package goexperiment

const StrictFIPSRuntime = false
const StrictFIPSRuntimeInt = 0
